### ISSUE TITLE
Inconsistency between code and documentation

### ISSUE THREAD

**Issue by pjmichalski** [dphansti/mango#11]
Hi,
The documentation states that the default FDR is 0.01 (and actually it lists FDR twice, which is strange, but both say default 0.01).  However, the default used in the code is 0.05.  I spent the past two days struggling to understand some results, and this was the source of my confusion.  Please update the documentation or change the default in the code.  

Thanks,
Paul

**Comment by dphansti** [comment]
Thanks for noticing this.  I updated the README to reflect the actual default settings.
