### ISSUE TITLE
how can mango build bedpe according to line-by-line matching from sam files of uniquely mapped reads 

### ISSUE THREAD

**Issue by hanbinlu** [dphansti/mango#16]
I read the code and other people's comment that mango builds bedpe by matching tag names of  2 sam files in a line-by-line manner.  But in the alignment step, -m option makes only uniquely mapped reads to be reported. So sam1 file and sam2 file should not be matching line-by-line.

**Comment by dphansti** [comment]
Bowtie returns a single line for every read when run with these parameters.  Non uniquely mapped reads are marked with a '*'.  The two files are matched.
