### ISSUE TITLE
"object gsize not found" in mango.R"

### ISSUE THREAD

**Issue by KojiMasuda** [dphansti/mango#4]
- Bug description:
  After downloading ChIA-PET data from https://www.encodedcc.org/datasets/ENCSR727WCB/,
  I got an error message saying "object gsize not found" at stage 4 of Mango.
- Actual behavior:
  when I run mango as follows,

`Rscript /pathtomango/mango.R --fastq1 SNY_K562_RAD21_0.0_r1.fastq --fastq2 SNY_K562_RAD21_0.0_r2.fastq --prefix SNY_K562_RAD21 --bowtieref /pathto/bowtie_index/hg19 --bedtoolsgenome /pathto/bedtoolsgenome/human.hg19.genome --chromexclude chrM,chrY --stages 1:5 --reportallpairs TRUE --MACS_qvalue 0.05`

The following error appeared at stage 4,

[1] "Starting mango ChIA PET analysis tool"
[1] "2015-12-28 22:17:43 JST"
[1] TRUE
[1] "finding linkers"
1000000
2000000
3000000
.......
1606000000
1607000000
1608000000
[1] "aligning reads"
[1] "score type detected: Sanger"
[1] "/bowtiepath/bowtie /pathto/bowtie_index/hg19 SNY_K562_RAD21_1.same.fastq SNY_K562_RAD21_1.same.sam --phred33-quals -S -v 0 -k 1 --chunkmbs 500 --sam-nohead --mapq 40 -m 1"
 reads processed: 296761755
 reads with at least one reported alignment: 168427037 (56.75%)
 reads that failed to align: 8328187 (2.81%)
 reads with alignments suppressed due to -m: 120006531 (40.44%)
Reported 168427037 alignments to 1 output stream(s)
[1] "score type detected: Sanger"
[1] "/bowtiepath/bowtie-1.0.0/bowtie /pathto/bowtie_index/hg19 SNY_K562_RAD21_2.same.fastq SNY_K562_RAD21_2.same.sam --phred33-quals -S -v 0 -k 1 --chunkmbs 500 --sam-nohead --mapq 40 -m 1"
 reads processed: 296761755
 reads with at least one reported alignment: 167864899 (56.57%)
 reads that failed to align: 8242851 (2.78%)
 reads with alignments suppressed due to -m: 120654005 (40.66%)
Reported 167864899 alignments to 1 output stream(s)
[1] "building bedpe"
[1] "removing duplicate PETs"
[1] "building tagAlign file"
[1] "calling peaks"
Error in paste(macs2path, " callpeak -t ", tagAlignfile, shiftsize, " -g ",  : 
  object 'gsize' not found
Calls: callpeaks -> paste
Execution halted
- Expected Behavior:
  Peakcalling by MACS2 with gsize of "hs".
- Testing Steps Attempted:
  I added the following line in mango.R file,

**gsize           = as.character(opt["gsize"])**

at line 316.

**And it worked fine! MACS2 detected 89605 peaks. Also, 9049 significant interactions were detected by Mango for Rad21.**
- Date Seen: 2015-12-28
- Versions:
  OS = LinuxMint 17.1
  Mango = version 1.0.5
  MACS2 = version 2.1.0.20151222
  bedtools = v2.17.0
- Severity: Major

**Comment by dphansti** [comment]
Thank you very much for finding this.  That bug has been fixed in version 1.0.7.
