### ISSUE TITLE
Nothing is written on the peaksfileslop

### ISSUE THREAD

**Issue by chadi-elfarran** [dphansti/mango#6]
Dear Admin,

Thank you very much for creating this wonderful tool and for maintaining it.

I am currently trying to analyse a published online CTCF ChIA-PET data set using mango.

The first three stages (1-3) work very well. However when stage 4 is reached, the .narrowPeak file is created and then the following messages are printed on the terminal:

[1] "extending peaks"
****\* ERROR: No input file given. Exiting. *****

I am using the following versions of the required programmes:

[1] "bedtools version: bedtools v2.21.0"
[1] "macs2 version: macs2 2.1.0.20150731"
[1] "bowtie version: bowtie version 1.1.1"

Can you kindly assist me on resolving the above mentioned issue.

Thanks a lot.

Best Regards,

Chadi

**Comment by dphansti** [comment]
Well that is not good.  I have a few questions.

How many lines are in the .narrowPeak file?

Are you running the pipeline all at once (i.e. --stages 1:5) or are you running one step at a time?  Mango is quite particular about filenames.  The prefix needs to be the same for all steps.

**Comment by chadi-elfarran** [comment]
Dear Dphansti,

Thank you for your reply. I run all the stages at once (from 1:5). The .narrowPeak file contains around 40000 lines.

Here is the script that I have used:
Rscript mango.R --fastq1 ~/Analysis/ChIA-PET/Raw/CTCF/CTCF_1.fastq --fastq2 ~/Analysis/ChIA-PET/Raw/CTCF/CTCF_2.fastq --prefix mango --stages 1:5 --outdir ~/Analysis/ChIA-PET/Mango/CTCF/ --bowtieref ~/Genomes/Bowtie/mm9/mm9 --bedtoolsgenome ~/Apps/mouse.mm9.genome --linkerA GTTGGATCCG --linkerB GTTGGATCAT --gsize mm --distcutrangemax 10000

I have also tried keeping the --distcutrangemax at 100K (the default value), but I got the same issue.

Best regards

**Comment by chadi-elfarran** [comment]
Dear D phansti,

The issue has been resolved by updating bedtools from v 2.21.0 to v 2.25.0.

Currently the pipeline works fine until the final stage (5) is reached. Towards the end, the following messages are printed on the pipeline:

[1] "extending peaks"
[1] "counting reads per peak"
[1] "determining self-ligation distance"
[1] "self-ligation cutoff = NA"
[1] "grouping PETs into interactions"
[1] "---Splitting PETs by chromosome"
[1] "---Intersecting PETs with peaks"
[1] "---Building putative interaction set"
[1] "modeling PETs based on peak depth and distance"
Error in splitdata[[i]] : subscript out of bounds
Calls: binmaker
Execution halted

Can you kindly assist me on resolving this issue?

Thanks

**Comment by chadi-elfarran** [comment]
Dear D phansti,

I have resolved the issue by increasing the --distcutrangemax from 10000 to 50000. I have also excluded Chromosome M from the analysis.

The pipeline works perfectly fine now.

Thanks for developing this great tool.

Best Regards,

Chadi

**Comment by dphansti** [comment]
Great!  I have added more detail to the README file to help explain recommended settings.  Yes, ChrM should always be excluded.  And I would not recommend changing distcutrangemin and distcutrangemax.  Mango will identify the correct cutoff.  These values just define what range to look for it.

**Comment by dphansti** [comment]
Great. I responded to your comment on github and added more info to the
README file.
